package proj.entity;
// Generated Nov 21, 2013 3:12:18 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import proj.util.HibernateUtil;

/**
 * SinhVien generated by hbm2java
 */
public class SinhVien  implements java.io.Serializable {
    private static Object cb;


     private int idSinhVien;
     private String masv;
     private Integer idConNguoi;
     private Integer idKhoaTs;
     private Integer idLopQuanLy;
     private int idCanBo;
     private String matKhau;
     private String hoten;
     private Set sinhVienDangKyHocs = new HashSet(0);
     private Set mienHocs = new HashSet(0);
     private Set ketQuaHocs = new HashSet(0);

    public SinhVien() {
    }

	
    public SinhVien(int idSinhVien, int idCanBo, String matKhau, String hoten) {
        this.idSinhVien = idSinhVien;
        this.idCanBo = idCanBo;
        this.matKhau = matKhau;
        this.hoten = hoten;
    }
    public SinhVien(int idSinhVien, String masv, Integer idConNguoi, Integer idKhoaTs, Integer idLopQuanLy, int idCanBo, String matKhau, String hoten, Set sinhVienDangKyHocs, Set mienHocs, Set ketQuaHocs) {
       this.idSinhVien = idSinhVien;
       this.masv = masv;
       this.idConNguoi = idConNguoi;
       this.idKhoaTs = idKhoaTs;
       this.idLopQuanLy = idLopQuanLy;
       this.idCanBo = idCanBo;
       this.matKhau = matKhau;
       this.hoten = hoten;
       this.sinhVienDangKyHocs = sinhVienDangKyHocs;
       this.mienHocs = mienHocs;
       this.ketQuaHocs = ketQuaHocs;
    }
   
    public int getIdSinhVien() {
        return this.idSinhVien;
    }
    
    public void setIdSinhVien(int idSinhVien) {
        this.idSinhVien = idSinhVien;
    }
    public String getMasv() {
        return this.masv;
    }
    
    public void setMasv(String masv) {
        this.masv = masv;
    }
    public Integer getIdConNguoi() {
        return this.idConNguoi;
    }
    
    public void setIdConNguoi(Integer idConNguoi) {
        this.idConNguoi = idConNguoi;
    }
    public Integer getIdKhoaTs() {
        return this.idKhoaTs;
    }
    
    public void setIdKhoaTs(Integer idKhoaTs) {
        this.idKhoaTs = idKhoaTs;
    }
    public Integer getIdLopQuanLy() {
        return this.idLopQuanLy;
    }
    
    public void setIdLopQuanLy(Integer idLopQuanLy) {
        this.idLopQuanLy = idLopQuanLy;
    }
    public int getIdCanBo() {
        return this.idCanBo;
    }
    
    public void setIdCanBo(int idCanBo) {
        this.idCanBo = idCanBo;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public Set getSinhVienDangKyHocs() {
        return this.sinhVienDangKyHocs;
    }
    
    public void setSinhVienDangKyHocs(Set sinhVienDangKyHocs) {
        this.sinhVienDangKyHocs = sinhVienDangKyHocs;
    }
    public Set getMienHocs() {
        return this.mienHocs;
    }
    
    public void setMienHocs(Set mienHocs) {
        this.mienHocs = mienHocs;
    }
    public Set getKetQuaHocs() {
        return this.ketQuaHocs;
    }
    
    public void setKetQuaHocs(Set ketQuaHocs) {
        this.ketQuaHocs = ketQuaHocs;
    }
public static void main(String[] args){
    
    //SinhVien sv = null;
    SessionFactory factory = HibernateUtil.getSessionFactory();
    Session session = factory.getCurrentSession();
    
    try{
        session.beginTransaction();
        session.save(cb);
        session.getTransaction().commit();
    }catch (Exception e){
        if(session.getTransaction().isActive()){
            session.getTransaction().rollback();
        }
        e.printStackTrace();
    }
}



}


