package proj.entity;
// Generated Oct 15, 2013 9:41:34 PM by Hibernate Tools 3.2.1.GA



/**
 * MienHoc generated by hbm2java
 */
public class MienHoc  implements java.io.Serializable {


     private MienHocId id;
     private LyDoMien lyDoMien;
     private MonHoc monHoc;
     private SinhVien sinhVien;

    public MienHoc() {
    }

    public MienHoc(MienHocId id, LyDoMien lyDoMien, MonHoc monHoc, SinhVien sinhVien) {
       this.id = id;
       this.lyDoMien = lyDoMien;
       this.monHoc = monHoc;
       this.sinhVien = sinhVien;
    }
   
    public MienHocId getId() {
        return this.id;
    }
    
    public void setId(MienHocId id) {
        this.id = id;
    }
    public LyDoMien getLyDoMien() {
        return this.lyDoMien;
    }
    
    public void setLyDoMien(LyDoMien lyDoMien) {
        this.lyDoMien = lyDoMien;
    }
    public MonHoc getMonHoc() {
        return this.monHoc;
    }
    
    public void setMonHoc(MonHoc monHoc) {
        this.monHoc = monHoc;
    }
    public SinhVien getSinhVien() {
        return this.sinhVien;
    }
    
    public void setSinhVien(SinhVien sinhVien) {
        this.sinhVien = sinhVien;
    }




}


