package proj.entity;
// Generated Oct 15, 2013 9:41:34 PM by Hibernate Tools 3.2.1.GA



/**
 * SinhVienDangKyHoc generated by hbm2java
 */
public class SinhVienDangKyHoc  implements java.io.Serializable {


     private SinhVienDangKyHocId id;
     private SinhVien sinhVien;
     private LopMonHoc lopMonHoc;
     private Integer trangThai;

    public SinhVienDangKyHoc() {
    }

	
    public SinhVienDangKyHoc(SinhVienDangKyHocId id, SinhVien sinhVien, LopMonHoc lopMonHoc) {
        this.id = id;
        this.sinhVien = sinhVien;
        this.lopMonHoc = lopMonHoc;
    }
    public SinhVienDangKyHoc(SinhVienDangKyHocId id, SinhVien sinhVien, LopMonHoc lopMonHoc, Integer trangThai) {
       this.id = id;
       this.sinhVien = sinhVien;
       this.lopMonHoc = lopMonHoc;
       this.trangThai = trangThai;
    }
   
    public SinhVienDangKyHocId getId() {
        return this.id;
    }
    
    public void setId(SinhVienDangKyHocId id) {
        this.id = id;
    }
    public SinhVien getSinhVien() {
        return this.sinhVien;
    }
    
    public void setSinhVien(SinhVien sinhVien) {
        this.sinhVien = sinhVien;
    }
    public LopMonHoc getLopMonHoc() {
        return this.lopMonHoc;
    }
    
    public void setLopMonHoc(LopMonHoc lopMonHoc) {
        this.lopMonHoc = lopMonHoc;
    }
    public Integer getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(Integer trangThai) {
        this.trangThai = trangThai;
    }




}


