package proj.entity;
// Generated Oct 15, 2013 9:41:34 PM by Hibernate Tools 3.2.1.GA



/**
 * SinhVienDangKyHocId generated by hbm2java
 */
public class SinhVienDangKyHocId  implements java.io.Serializable {


     private int idSinhVien;
     private int idLopMonHoc;

    public SinhVienDangKyHocId() {
    }

    public SinhVienDangKyHocId(int idSinhVien, int idLopMonHoc) {
       this.idSinhVien = idSinhVien;
       this.idLopMonHoc = idLopMonHoc;
    }
   
    public int getIdSinhVien() {
        return this.idSinhVien;
    }
    
    public void setIdSinhVien(int idSinhVien) {
        this.idSinhVien = idSinhVien;
    }
    public int getIdLopMonHoc() {
        return this.idLopMonHoc;
    }
    
    public void setIdLopMonHoc(int idLopMonHoc) {
        this.idLopMonHoc = idLopMonHoc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SinhVienDangKyHocId) ) return false;
		 SinhVienDangKyHocId castOther = ( SinhVienDangKyHocId ) other; 
         
		 return (this.getIdSinhVien()==castOther.getIdSinhVien())
 && (this.getIdLopMonHoc()==castOther.getIdLopMonHoc());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSinhVien();
         result = 37 * result + this.getIdLopMonHoc();
         return result;
   }   


}


