package proj.entity;
// Generated Oct 15, 2013 9:41:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CanBo generated by hbm2java
 */
public class CanBo  implements java.io.Serializable {


     private int idCanBo;
     private String macb;
     private Integer idConNguoi;
     private Integer idLoaiCanBo;
     private String tdVanHoa;
     private Integer idHocVi;
     private Integer idHocHam;
     private Integer idNgach;
     private Integer bac;
     private Integer heSo;
     private Integer idTrinhDoNgoaiNgu;
     private Integer gioNghiaVu;
     private Set<LopMonHoc> lopMonHocs = new HashSet<LopMonHoc>(0);

    public CanBo() {
    }

	
    public CanBo(int idCanBo) {
        this.idCanBo = idCanBo;
    }
    public CanBo(int idCanBo, String macb, Integer idConNguoi, Integer idLoaiCanBo, String tdVanHoa, Integer idHocVi, Integer idHocHam, Integer idNgach, Integer bac, Integer heSo, Integer idTrinhDoNgoaiNgu, Integer gioNghiaVu, Set<LopMonHoc> lopMonHocs) {
       this.idCanBo = idCanBo;
       this.macb = macb;
       this.idConNguoi = idConNguoi;
       this.idLoaiCanBo = idLoaiCanBo;
       this.tdVanHoa = tdVanHoa;
       this.idHocVi = idHocVi;
       this.idHocHam = idHocHam;
       this.idNgach = idNgach;
       this.bac = bac;
       this.heSo = heSo;
       this.idTrinhDoNgoaiNgu = idTrinhDoNgoaiNgu;
       this.gioNghiaVu = gioNghiaVu;
       this.lopMonHocs = lopMonHocs;
    }
   
    public int getIdCanBo() {
        return this.idCanBo;
    }
    
    public void setIdCanBo(int idCanBo) {
        this.idCanBo = idCanBo;
    }
    public String getMacb() {
        return this.macb;
    }
    
    public void setMacb(String macb) {
        this.macb = macb;
    }
    public Integer getIdConNguoi() {
        return this.idConNguoi;
    }
    
    public void setIdConNguoi(Integer idConNguoi) {
        this.idConNguoi = idConNguoi;
    }
    public Integer getIdLoaiCanBo() {
        return this.idLoaiCanBo;
    }
    
    public void setIdLoaiCanBo(Integer idLoaiCanBo) {
        this.idLoaiCanBo = idLoaiCanBo;
    }
    public String getTdVanHoa() {
        return this.tdVanHoa;
    }
    
    public void setTdVanHoa(String tdVanHoa) {
        this.tdVanHoa = tdVanHoa;
    }
    public Integer getIdHocVi() {
        return this.idHocVi;
    }
    
    public void setIdHocVi(Integer idHocVi) {
        this.idHocVi = idHocVi;
    }
    public Integer getIdHocHam() {
        return this.idHocHam;
    }
    
    public void setIdHocHam(Integer idHocHam) {
        this.idHocHam = idHocHam;
    }
    public Integer getIdNgach() {
        return this.idNgach;
    }
    
    public void setIdNgach(Integer idNgach) {
        this.idNgach = idNgach;
    }
    public Integer getBac() {
        return this.bac;
    }
    
    public void setBac(Integer bac) {
        this.bac = bac;
    }
    public Integer getHeSo() {
        return this.heSo;
    }
    
    public void setHeSo(Integer heSo) {
        this.heSo = heSo;
    }
    public Integer getIdTrinhDoNgoaiNgu() {
        return this.idTrinhDoNgoaiNgu;
    }
    
    public void setIdTrinhDoNgoaiNgu(Integer idTrinhDoNgoaiNgu) {
        this.idTrinhDoNgoaiNgu = idTrinhDoNgoaiNgu;
    }
    public Integer getGioNghiaVu() {
        return this.gioNghiaVu;
    }
    
    public void setGioNghiaVu(Integer gioNghiaVu) {
        this.gioNghiaVu = gioNghiaVu;
    }
    public Set<LopMonHoc> getLopMonHocs() {
        return this.lopMonHocs;
    }
    
    public void setLopMonHocs(Set<LopMonHoc> lopMonHocs) {
        this.lopMonHocs = lopMonHocs;
    }




}


