package proj.entity;
// Generated Oct 15, 2013 9:41:34 PM by Hibernate Tools 3.2.1.GA



/**
 * KetQuaHoc generated by hbm2java
 */
public class KetQuaHoc  implements java.io.Serializable {


     private KetQuaHocId id;
     private MonHoc monHoc;
     private SinhVien sinhVien;
     private LopMonHoc lopMonHoc;
     private Integer diemSo;
     private String diemChu;
     private Boolean tichLuy;

    public KetQuaHoc() {
    }

	
    public KetQuaHoc(KetQuaHocId id, MonHoc monHoc, SinhVien sinhVien, LopMonHoc lopMonHoc) {
        this.id = id;
        this.monHoc = monHoc;
        this.sinhVien = sinhVien;
        this.lopMonHoc = lopMonHoc;
    }
    public KetQuaHoc(KetQuaHocId id, MonHoc monHoc, SinhVien sinhVien, LopMonHoc lopMonHoc, Integer diemSo, String diemChu, Boolean tichLuy) {
       this.id = id;
       this.monHoc = monHoc;
       this.sinhVien = sinhVien;
       this.lopMonHoc = lopMonHoc;
       this.diemSo = diemSo;
       this.diemChu = diemChu;
       this.tichLuy = tichLuy;
    }
   
    public KetQuaHocId getId() {
        return this.id;
    }
    
    public void setId(KetQuaHocId id) {
        this.id = id;
    }
    public MonHoc getMonHoc() {
        return this.monHoc;
    }
    
    public void setMonHoc(MonHoc monHoc) {
        this.monHoc = monHoc;
    }
    public SinhVien getSinhVien() {
        return this.sinhVien;
    }
    
    public void setSinhVien(SinhVien sinhVien) {
        this.sinhVien = sinhVien;
    }
    public LopMonHoc getLopMonHoc() {
        return this.lopMonHoc;
    }
    
    public void setLopMonHoc(LopMonHoc lopMonHoc) {
        this.lopMonHoc = lopMonHoc;
    }
    public Integer getDiemSo() {
        return this.diemSo;
    }
    
    public void setDiemSo(Integer diemSo) {
        this.diemSo = diemSo;
    }
    public String getDiemChu() {
        return this.diemChu;
    }
    
    public void setDiemChu(String diemChu) {
        this.diemChu = diemChu;
    }
    public Boolean getTichLuy() {
        return this.tichLuy;
    }
    
    public void setTichLuy(Boolean tichLuy) {
        this.tichLuy = tichLuy;
    }




}


