package proj.entity;
// Generated Oct 15, 2013 9:41:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import proj.util.HibernateUtil;

/**
 * LyDoMien generated by hbm2java
 */
public class LyDoMien  implements java.io.Serializable {


     private int idLyDoMien;
     private String lyDo;
     private Set<MienHoc> mienHocs = new HashSet<MienHoc>(0);

    public LyDoMien() {
    }

	
    public LyDoMien(int idLyDoMien) {
        this.idLyDoMien = idLyDoMien;
    }
    public LyDoMien(int idLyDoMien, String lyDo, Set<MienHoc> mienHocs) {
       this.idLyDoMien = idLyDoMien;
       this.lyDo = lyDo;
       this.mienHocs = mienHocs;
    }
   
    public int getIdLyDoMien() {
        return this.idLyDoMien;
    }
    
    public void setIdLyDoMien(int idLyDoMien) {
        this.idLyDoMien = idLyDoMien;
    }
    public String getLyDo() {
        return this.lyDo;
    }
    
    public void setLyDo(String lyDo) {
        this.lyDo = lyDo;
    }
    public Set<MienHoc> getMienHocs() {
        return this.mienHocs;
    }
    
    public void setMienHocs(Set<MienHoc> mienHocs) {
        this.mienHocs = mienHocs;
    }

   

}


