package proj.entity;
// Generated Oct 15, 2013 9:41:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SinhVien generated by hbm2java
 */
public class SinhVien  implements java.io.Serializable {


     private int idSinhVien;
     private String masv;
     private Integer idConNguoi;
     private Integer idKhoaTs;
     private Integer idLopQuanLy;
     private Set<SinhVienDangKyHoc> sinhVienDangKyHocs = new HashSet<SinhVienDangKyHoc>(0);
     private Set<MienHoc> mienHocs = new HashSet<MienHoc>(0);
     private Set<KetQuaHoc> ketQuaHocs = new HashSet<KetQuaHoc>(0);

    public SinhVien() {
    }

	
    public SinhVien(int idSinhVien) {
        this.idSinhVien = idSinhVien;
    }
    public SinhVien(int idSinhVien, String masv, Integer idConNguoi, Integer idKhoaTs, Integer idLopQuanLy, Set<SinhVienDangKyHoc> sinhVienDangKyHocs, Set<MienHoc> mienHocs, Set<KetQuaHoc> ketQuaHocs) {
       this.idSinhVien = idSinhVien;
       this.masv = masv;
       this.idConNguoi = idConNguoi;
       this.idKhoaTs = idKhoaTs;
       this.idLopQuanLy = idLopQuanLy;
       this.sinhVienDangKyHocs = sinhVienDangKyHocs;
       this.mienHocs = mienHocs;
       this.ketQuaHocs = ketQuaHocs;
    }
   
    public int getIdSinhVien() {
        return this.idSinhVien;
    }
    
    public void setIdSinhVien(int idSinhVien) {
        this.idSinhVien = idSinhVien;
    }
    public String getMasv() {
        return this.masv;
    }
    
    public void setMasv(String masv) {
        this.masv = masv;
    }
    public Integer getIdConNguoi() {
        return this.idConNguoi;
    }
    
    public void setIdConNguoi(Integer idConNguoi) {
        this.idConNguoi = idConNguoi;
    }
    public Integer getIdKhoaTs() {
        return this.idKhoaTs;
    }
    
    public void setIdKhoaTs(Integer idKhoaTs) {
        this.idKhoaTs = idKhoaTs;
    }
    public Integer getIdLopQuanLy() {
        return this.idLopQuanLy;
    }
    
    public void setIdLopQuanLy(Integer idLopQuanLy) {
        this.idLopQuanLy = idLopQuanLy;
    }
    public Set<SinhVienDangKyHoc> getSinhVienDangKyHocs() {
        return this.sinhVienDangKyHocs;
    }
    
    public void setSinhVienDangKyHocs(Set<SinhVienDangKyHoc> sinhVienDangKyHocs) {
        this.sinhVienDangKyHocs = sinhVienDangKyHocs;
    }
    public Set<MienHoc> getMienHocs() {
        return this.mienHocs;
    }
    
    public void setMienHocs(Set<MienHoc> mienHocs) {
        this.mienHocs = mienHocs;
    }
    public Set<KetQuaHoc> getKetQuaHocs() {
        return this.ketQuaHocs;
    }
    
    public void setKetQuaHocs(Set<KetQuaHoc> ketQuaHocs) {
        this.ketQuaHocs = ketQuaHocs;
    }




}


