package proj.entity;
// Generated Nov 21, 2013 3:12:18 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * NienKhoaHocKy generated by hbm2java
 */
public class NienKhoaHocKy  implements java.io.Serializable {


     private int idNienKhoaHocKy;
     private Integer hocKy;
     private Integer nam1;
     private Integer nam2;
     private Set lopMonHocs = new HashSet(0);

    public NienKhoaHocKy() {
    }

	
    public NienKhoaHocKy(int idNienKhoaHocKy) {
        this.idNienKhoaHocKy = idNienKhoaHocKy;
    }
    public NienKhoaHocKy(int idNienKhoaHocKy, Integer hocKy, Integer nam1, Integer nam2, Set lopMonHocs) {
       this.idNienKhoaHocKy = idNienKhoaHocKy;
       this.hocKy = hocKy;
       this.nam1 = nam1;
       this.nam2 = nam2;
       this.lopMonHocs = lopMonHocs;
    }
   
    public int getIdNienKhoaHocKy() {
        return this.idNienKhoaHocKy;
    }
    
    public void setIdNienKhoaHocKy(int idNienKhoaHocKy) {
        this.idNienKhoaHocKy = idNienKhoaHocKy;
    }
    public Integer getHocKy() {
        return this.hocKy;
    }
    
    public void setHocKy(Integer hocKy) {
        this.hocKy = hocKy;
    }
    public Integer getNam1() {
        return this.nam1;
    }
    
    public void setNam1(Integer nam1) {
        this.nam1 = nam1;
    }
    public Integer getNam2() {
        return this.nam2;
    }
    
    public void setNam2(Integer nam2) {
        this.nam2 = nam2;
    }
    public Set getLopMonHocs() {
        return this.lopMonHocs;
    }
    
    public void setLopMonHocs(Set lopMonHocs) {
        this.lopMonHocs = lopMonHocs;
    }




}


